/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import cloudapp.ConfigClientApplication;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        ConfigClientApplication classUnderTest = new ConfigClientApplication();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
